export type ThemeChoice =
  | "nullkeys-classic"
  | "legacy-dark"
  | "light-paper"
  | "dracula"
  | "nord"
  | "solarized-dark"
  | "solarized-light"
  | "gruvbox-dark"
  | "gruvbox-light"
  | "catppuccin-mocha"
  | "catppuccin-latte"
  | "catppuccin-frappe"
  | "catppuccin-macchiato";

export interface ThemeDefinition {
  id: ThemeChoice;
  label: string;
  description: string;
  mode: "light" | "dark";
  cssVariables: Record<`--${string}`, string>;
}

interface ThemeTokenInput {
  canvasTop: string;
  canvas: string;
  canvasBottom: string;
  panel: string;
  panelMuted: string;
  panelSolid: string;
  accent: string;
  accentSoft: string;
  text: string;
  textMuted: string;
  borderTone: string;
  danger: string;
  success: string;
  warn: string;
  overlayBackdrop: string;
  modalSurface: string;
  modalSurfaceMuted: string;
  modalText: string;
  modalTextMuted: string;
  modalBorder: string;
  modalShadow: string;
  popoverSurface: string;
  popoverText: string;
  popoverBorder: string;
  surfaceRaised: string;
  surfaceInset: string;
  surfaceStrong: string;
  surfaceStrongHover: string;
  surfaceStrongText: string;
  focusRing: string;
  trendUp: string;
  trendDown: string;
  chipMutedBackground: string;
  chipMutedBorder: string;
  chipMutedText: string;
  chipActiveBackground: string;
  chipActiveBorder: string;
  chipActiveText: string;
  chipWarningBackground: string;
  chipWarningBorder: string;
  chipWarningText: string;
  chipSelectedBackground: string;
  chipSelectedBorder: string;
  chipSelectedText: string;
}

function buildThemeVariables(input: ThemeTokenInput) {
  return {
    "--canvas-top": input.canvasTop,
    "--canvas": input.canvas,
    "--canvas-bottom": input.canvasBottom,
    "--panel": input.panel,
    "--panel-muted": input.panelMuted,
    "--panel-solid": input.panelSolid,
    "--accent": input.accent,
    "--accent-soft": input.accentSoft,
    "--text": input.text,
    "--text-muted": input.textMuted,
    "--border-tone": input.borderTone,
    "--danger": input.danger,
    "--success": input.success,
    "--warn": input.warn,
    "--overlay-backdrop": input.overlayBackdrop,
    "--modal-surface": input.modalSurface,
    "--modal-surface-muted": input.modalSurfaceMuted,
    "--modal-text": input.modalText,
    "--modal-text-muted": input.modalTextMuted,
    "--modal-border": input.modalBorder,
    "--modal-shadow": input.modalShadow,
    "--popover-surface": input.popoverSurface,
    "--popover-text": input.popoverText,
    "--popover-border": input.popoverBorder,
    "--surface-raised": input.surfaceRaised,
    "--surface-inset": input.surfaceInset,
    "--surface-strong": input.surfaceStrong,
    "--surface-strong-hover": input.surfaceStrongHover,
    "--surface-strong-text": input.surfaceStrongText,
    "--focus-ring": input.focusRing,
    "--trend-up": input.trendUp,
    "--trend-down": input.trendDown,
    "--chip-muted-background": input.chipMutedBackground,
    "--chip-muted-border": input.chipMutedBorder,
    "--chip-muted-text": input.chipMutedText,
    "--chip-active-background": input.chipActiveBackground,
    "--chip-active-border": input.chipActiveBorder,
    "--chip-active-text": input.chipActiveText,
    "--chip-warning-background": input.chipWarningBackground,
    "--chip-warning-border": input.chipWarningBorder,
    "--chip-warning-text": input.chipWarningText,
    "--chip-selected-background": input.chipSelectedBackground,
    "--chip-selected-border": input.chipSelectedBorder,
    "--chip-selected-text": input.chipSelectedText,
  } satisfies Record<`--${string}`, string>;
}

function normalizeHex(color: string) {
  const normalizedColor = color.trim().replace(/^#/u, "");

  if (normalizedColor.length === 3) {
    return normalizedColor
      .split("")
      .map((character) => `${character}${character}`)
      .join("");
  }

  return normalizedColor;
}

export function hexToHslTriplet(color: string) {
  const normalizedColor = normalizeHex(color);
  const red = Number.parseInt(normalizedColor.slice(0, 2), 16) / 255;
  const green = Number.parseInt(normalizedColor.slice(2, 4), 16) / 255;
  const blue = Number.parseInt(normalizedColor.slice(4, 6), 16) / 255;
  const maxChannel = Math.max(red, green, blue);
  const minChannel = Math.min(red, green, blue);
  const lightness = (maxChannel + minChannel) / 2;
  const delta = maxChannel - minChannel;
  let hue = 0;
  let saturation = 0;

  if (delta !== 0) {
    saturation =
      lightness > 0.5 ? delta / (2 - maxChannel - minChannel) : delta / (maxChannel + minChannel);

    switch (maxChannel) {
      case red:
        hue = (green - blue) / delta + (green < blue ? 6 : 0);
        break;
      case green:
        hue = (blue - red) / delta + 2;
        break;
      default:
        hue = (red - green) / delta + 4;
        break;
    }

    hue /= 6;
  }

  return `${Math.round(hue * 360)} ${Math.round(saturation * 100)}% ${Math.round(lightness * 100)}%`;
}

function buildThemeVariablesFromHex(input: ThemeTokenInput) {
  return buildThemeVariables(
    Object.fromEntries(
      Object.entries(input).map(([tokenName, tokenValue]) => [tokenName, hexToHslTriplet(tokenValue)]),
    ) as unknown as ThemeTokenInput,
  );
}

export const themeReferencePalettes = {
  dracula: {
    background: "#282a36",
    currentLine: "#44475a",
    foreground: "#f8f8f2",
    comment: "#6272a4",
    cyan: "#8be9fd",
    green: "#50fa7b",
    orange: "#ffb86c",
    pink: "#ff79c6",
    purple: "#bd93f9",
    red: "#ff5555",
    yellow: "#f1fa8c",
  },
  nord: {
    nord0: "#2e3440",
    nord1: "#3b4252",
    nord2: "#434c5e",
    nord3: "#4c566a",
    snow0: "#d8dee9",
    snow1: "#e5e9f0",
    snow2: "#eceff4",
    frost1: "#8fbcbb",
    frost2: "#88c0d0",
    frost3: "#81a1c1",
    frost4: "#5e81ac",
    red: "#bf616a",
    orange: "#d08770",
    yellow: "#ebcb8b",
    green: "#a3be8c",
    purple: "#b48ead",
  },
  solarized: {
    base03: "#002b36",
    base02: "#073642",
    base01: "#586e75",
    base00: "#657b83",
    base0: "#839496",
    base1: "#93a1a1",
    base2: "#eee8d5",
    base3: "#fdf6e3",
    yellow: "#b58900",
    orange: "#cb4b16",
    red: "#dc322f",
    magenta: "#d33682",
    violet: "#6c71c4",
    blue: "#268bd2",
    cyan: "#2aa198",
    green: "#859900",
  },
  gruvboxDark: {
    bg0: "#282828",
    bg1: "#3c3836",
    bg2: "#504945",
    bg3: "#665c54",
    fg0: "#fbf1c7",
    fg1: "#ebdbb2",
    fg2: "#d5c4a1",
    fg3: "#bdae93",
    fg4: "#a89984",
    red: "#fb4934",
    green: "#b8bb26",
    yellow: "#fabd2f",
    blue: "#83a598",
    purple: "#d3869b",
    aqua: "#8ec07c",
    orange: "#fe8019",
  },
  gruvboxLight: {
    bg0: "#fbf1c7",
    bg1: "#ebdbb2",
    bg2: "#d5c4a1",
    bg3: "#bdae93",
    fg0: "#282828",
    fg1: "#3c3836",
    fg2: "#504945",
    fg3: "#665c54",
    fg4: "#7c6f64",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    purple: "#b16286",
    aqua: "#689d6a",
    orange: "#d65d0e",
  },
  catppuccinMocha: {
    crust: "#11111b",
    mantle: "#181825",
    base: "#1e1e2e",
    surface0: "#313244",
    surface1: "#45475a",
    surface2: "#585b70",
    overlay0: "#6c7086",
    overlay1: "#7f849c",
    overlay2: "#9399b2",
    subtext0: "#a6adc8",
    subtext1: "#bac2de",
    text: "#cdd6f4",
    mauve: "#cba6f7",
    red: "#f38ba8",
    peach: "#fab387",
    yellow: "#f9e2af",
    green: "#a6e3a1",
    sky: "#89dceb",
    sapphire: "#74c7ec",
    blue: "#89b4fa",
    lavender: "#b4befe",
  },
  catppuccinLatte: {
    crust: "#dce0e8",
    mantle: "#e6e9ef",
    base: "#eff1f5",
    surface0: "#ccd0da",
    surface1: "#bcc0cc",
    surface2: "#acb0be",
    overlay0: "#9ca0b0",
    overlay1: "#8c8fa1",
    overlay2: "#7c7f93",
    subtext0: "#6c6f85",
    subtext1: "#5c5f77",
    text: "#4c4f69",
    mauve: "#8839ef",
    red: "#d20f39",
    peach: "#fe640b",
    yellow: "#df8e1d",
    green: "#40a02b",
    sky: "#04a5e5",
    sapphire: "#209fb5",
    blue: "#1e66f5",
    lavender: "#7287fd",
  },
  catppuccinFrappe: {
    crust: "#232634",
    mantle: "#292c3c",
    base: "#303446",
    surface0: "#414559",
    surface1: "#51576d",
    surface2: "#626880",
    overlay0: "#737994",
    overlay1: "#838ba7",
    overlay2: "#949cbb",
    subtext0: "#a5adce",
    subtext1: "#b5bfe2",
    text: "#c6d0f5",
    mauve: "#ca9ee6",
    red: "#e78284",
    peach: "#ef9f76",
    yellow: "#e5c890",
    green: "#a6d189",
    sky: "#99d1db",
    sapphire: "#85c1dc",
    blue: "#8caaee",
    lavender: "#babbf1",
  },
  catppuccinMacchiato: {
    crust: "#181926",
    mantle: "#1e2030",
    base: "#24273a",
    surface0: "#363a4f",
    surface1: "#494d64",
    surface2: "#5b6078",
    overlay0: "#6e738d",
    overlay1: "#8087a2",
    overlay2: "#939ab7",
    subtext0: "#a5adcb",
    subtext1: "#b8c0e0",
    text: "#cad3f5",
    mauve: "#c6a0f6",
    red: "#ed8796",
    peach: "#f5a97f",
    yellow: "#eed49f",
    green: "#a6da95",
    sky: "#91d7e3",
    sapphire: "#7dc4e4",
    blue: "#8aadf4",
    lavender: "#b7bdf8",
  },
} as const;

const draculaPalette = themeReferencePalettes.dracula;
const nordPalette = themeReferencePalettes.nord;
const solarizedPalette = themeReferencePalettes.solarized;
const gruvboxDarkPalette = themeReferencePalettes.gruvboxDark;
const gruvboxLightPalette = themeReferencePalettes.gruvboxLight;
const catppuccinMochaPalette = themeReferencePalettes.catppuccinMocha;
const catppuccinLattePalette = themeReferencePalettes.catppuccinLatte;
const catppuccinFrappePalette = themeReferencePalettes.catppuccinFrappe;
const catppuccinMacchiatoPalette = themeReferencePalettes.catppuccinMacchiato;

export const themeLibrary: ThemeDefinition[] = [
  {
    id: "nullkeys-classic",
    label: "NullKeys Classic",
    description: "Warm paper, olive accents, and a familiar classic teaching feel.",
    mode: "light",
    cssVariables: buildThemeVariables({
      canvasTop: "20 28% 95%",
      canvas: "22 24% 92%",
      canvasBottom: "24 18% 88%",
      panel: "22 30% 96%",
      panelMuted: "24 16% 88%",
      panelSolid: "24 24% 94%",
      accent: "110 24% 42%",
      accentSoft: "108 26% 83%",
      text: "238 16% 22%",
      textMuted: "243 7% 42%",
      borderTone: "24 10% 72%",
      danger: "3 44% 48%",
      success: "110 26% 38%",
      warn: "42 40% 42%",
      overlayBackdrop: "222 32% 10%",
      modalSurface: "30 32% 98%",
      modalSurfaceMuted: "28 18% 93%",
      modalText: "238 16% 20%",
      modalTextMuted: "240 9% 38%",
      modalBorder: "24 16% 70%",
      modalShadow: "228 24% 8%",
      popoverSurface: "28 26% 97%",
      popoverText: "238 16% 22%",
      popoverBorder: "24 12% 74%",
      surfaceRaised: "24 26% 95%",
      surfaceInset: "24 20% 93%",
      surfaceStrong: "214 18% 34%",
      surfaceStrongHover: "214 20% 28%",
      surfaceStrongText: "48 28% 93%",
      focusRing: "108 22% 34%",
      trendUp: "110 26% 40%",
      trendDown: "4 36% 48%",
      chipMutedBackground: "74 22% 52%",
      chipMutedBorder: "38 12% 70%",
      chipMutedText: "54 28% 92%",
      chipActiveBackground: "80 29% 67%",
      chipActiveBorder: "86 19% 48%",
      chipActiveText: "104 24% 18%",
      chipWarningBackground: "48 34% 67%",
      chipWarningBorder: "42 22% 50%",
      chipWarningText: "38 30% 18%",
      chipSelectedBackground: "102 24% 63%",
      chipSelectedBorder: "104 22% 44%",
      chipSelectedText: "104 28% 16%",
    }),
  },
  {
    id: "legacy-dark",
    label: "Legacy-style Dark",
    description: "A restrained charcoal training theme with high-contrast accents.",
    mode: "dark",
    cssVariables: buildThemeVariables({
      canvasTop: "225 17% 13%",
      canvas: "224 18% 10%",
      canvasBottom: "228 20% 8%",
      panel: "225 15% 14%",
      panelMuted: "224 12% 18%",
      panelSolid: "223 14% 17%",
      accent: "112 30% 56%",
      accentSoft: "116 20% 24%",
      text: "40 18% 92%",
      textMuted: "220 9% 68%",
      borderTone: "224 10% 27%",
      danger: "6 72% 62%",
      success: "112 30% 56%",
      warn: "39 80% 63%",
      overlayBackdrop: "224 32% 4%",
      modalSurface: "223 16% 15%",
      modalSurfaceMuted: "223 14% 19%",
      modalText: "40 18% 94%",
      modalTextMuted: "218 12% 76%",
      modalBorder: "223 12% 30%",
      modalShadow: "228 42% 2%",
      popoverSurface: "224 16% 16%",
      popoverText: "40 18% 94%",
      popoverBorder: "223 12% 28%",
      surfaceRaised: "223 15% 17%",
      surfaceInset: "224 13% 15%",
      surfaceStrong: "112 24% 52%",
      surfaceStrongHover: "112 26% 58%",
      surfaceStrongText: "116 28% 12%",
      focusRing: "112 30% 58%",
      trendUp: "110 44% 60%",
      trendDown: "4 70% 66%",
      chipMutedBackground: "78 24% 33%",
      chipMutedBorder: "80 14% 44%",
      chipMutedText: "52 34% 92%",
      chipActiveBackground: "86 26% 54%",
      chipActiveBorder: "84 20% 64%",
      chipActiveText: "106 24% 14%",
      chipWarningBackground: "46 28% 50%",
      chipWarningBorder: "44 20% 62%",
      chipWarningText: "38 38% 14%",
      chipSelectedBackground: "102 24% 58%",
      chipSelectedBorder: "102 24% 68%",
      chipSelectedText: "104 28% 12%",
    }),
  },
  {
    id: "light-paper",
    label: "Light Paper",
    description: "Bright, neutral paper with crisp slate text.",
    mode: "light",
    cssVariables: buildThemeVariables({
      canvasTop: "210 38% 98%",
      canvas: "210 26% 96%",
      canvasBottom: "208 18% 92%",
      panel: "0 0% 100%",
      panelMuted: "210 22% 92%",
      panelSolid: "210 26% 96%",
      accent: "210 78% 46%",
      accentSoft: "210 88% 91%",
      text: "220 20% 18%",
      textMuted: "220 10% 42%",
      borderTone: "216 14% 78%",
      danger: "2 72% 50%",
      success: "142 62% 34%",
      warn: "34 82% 44%",
      overlayBackdrop: "220 30% 8%",
      modalSurface: "0 0% 100%",
      modalSurfaceMuted: "210 28% 96%",
      modalText: "220 20% 15%",
      modalTextMuted: "220 10% 36%",
      modalBorder: "216 16% 76%",
      modalShadow: "220 32% 10%",
      popoverSurface: "0 0% 100%",
      popoverText: "220 20% 18%",
      popoverBorder: "216 14% 78%",
      surfaceRaised: "0 0% 100%",
      surfaceInset: "210 28% 96%",
      surfaceStrong: "216 52% 28%",
      surfaceStrongHover: "216 56% 24%",
      surfaceStrongText: "210 40% 98%",
      focusRing: "210 78% 44%",
      trendUp: "142 62% 34%",
      trendDown: "2 72% 48%",
      chipMutedBackground: "214 22% 54%",
      chipMutedBorder: "214 14% 72%",
      chipMutedText: "210 40% 98%",
      chipActiveBackground: "210 76% 78%",
      chipActiveBorder: "210 54% 48%",
      chipActiveText: "220 30% 18%",
      chipWarningBackground: "38 86% 76%",
      chipWarningBorder: "34 60% 50%",
      chipWarningText: "28 38% 20%",
      chipSelectedBackground: "145 42% 74%",
      chipSelectedBorder: "145 34% 44%",
      chipSelectedText: "148 48% 18%",
    }),
  },
  {
    id: "dracula",
    label: "Dracula",
    description: "Official Dracula contrast: violet charcoal, neon cyan focus, and pink-led accents.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: "#343746",
      canvas: draculaPalette.background,
      canvasBottom: "#21222c",
      panel: "#303341",
      panelMuted: draculaPalette.currentLine,
      panelSolid: "#393c4c",
      accent: draculaPalette.pink,
      accentSoft: draculaPalette.purple,
      text: draculaPalette.foreground,
      textMuted: draculaPalette.comment,
      borderTone: draculaPalette.currentLine,
      danger: draculaPalette.red,
      success: draculaPalette.green,
      warn: draculaPalette.orange,
      overlayBackdrop: "#11111b",
      modalSurface: "#303341",
      modalSurfaceMuted: "#393c4c",
      modalText: draculaPalette.foreground,
      modalTextMuted: draculaPalette.comment,
      modalBorder: draculaPalette.currentLine,
      modalShadow: "#11111b",
      popoverSurface: "#303341",
      popoverText: draculaPalette.foreground,
      popoverBorder: draculaPalette.currentLine,
      surfaceRaised: "#303341",
      surfaceInset: draculaPalette.background,
      surfaceStrong: draculaPalette.purple,
      surfaceStrongHover: "#d2b4fc",
      surfaceStrongText: "#1e1f29",
      focusRing: draculaPalette.cyan,
      trendUp: draculaPalette.green,
      trendDown: draculaPalette.red,
      chipMutedBackground: draculaPalette.comment,
      chipMutedBorder: draculaPalette.currentLine,
      chipMutedText: draculaPalette.foreground,
      chipActiveBackground: draculaPalette.cyan,
      chipActiveBorder: draculaPalette.purple,
      chipActiveText: "#1e1f29",
      chipWarningBackground: draculaPalette.yellow,
      chipWarningBorder: draculaPalette.orange,
      chipWarningText: "#3a3c4e",
      chipSelectedBackground: draculaPalette.green,
      chipSelectedBorder: "#6dff97",
      chipSelectedText: "#17311f",
    }),
  },
  {
    id: "nord",
    label: "Nord",
    description: "Official Nord balance: arctic blue surfaces, snow text, and restrained frost accents.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: nordPalette.nord1,
      canvas: nordPalette.nord0,
      canvasBottom: "#242933",
      panel: nordPalette.nord1,
      panelMuted: nordPalette.nord2,
      panelSolid: nordPalette.nord2,
      accent: nordPalette.frost4,
      accentSoft: nordPalette.nord3,
      text: nordPalette.snow1,
      textMuted: nordPalette.snow0,
      borderTone: nordPalette.nord3,
      danger: nordPalette.red,
      success: nordPalette.green,
      warn: nordPalette.yellow,
      overlayBackdrop: "#1f242d",
      modalSurface: nordPalette.nord1,
      modalSurfaceMuted: nordPalette.nord2,
      modalText: nordPalette.snow2,
      modalTextMuted: nordPalette.snow0,
      modalBorder: nordPalette.nord3,
      modalShadow: "#161a21",
      popoverSurface: nordPalette.nord1,
      popoverText: nordPalette.snow2,
      popoverBorder: nordPalette.nord3,
      surfaceRaised: nordPalette.nord2,
      surfaceInset: nordPalette.nord0,
      surfaceStrong: nordPalette.frost3,
      surfaceStrongHover: "#8aaed0",
      surfaceStrongText: "#202733",
      focusRing: nordPalette.frost2,
      trendUp: nordPalette.green,
      trendDown: nordPalette.red,
      chipMutedBackground: nordPalette.nord3,
      chipMutedBorder: nordPalette.nord2,
      chipMutedText: nordPalette.snow2,
      chipActiveBackground: nordPalette.frost2,
      chipActiveBorder: nordPalette.frost4,
      chipActiveText: "#202733",
      chipWarningBackground: nordPalette.yellow,
      chipWarningBorder: nordPalette.orange,
      chipWarningText: "#2f2a21",
      chipSelectedBackground: nordPalette.green,
      chipSelectedBorder: nordPalette.frost1,
      chipSelectedText: "#243126",
    }),
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    description: "Solarized Dark with the canonical base03/base02 hierarchy and restrained accent roles.",
    mode: "dark",
    // Solarized body text is lifted to base1 so long practice passages stay readable while the base03/base02 structure remains canonical.
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: solarizedPalette.base02,
      canvas: solarizedPalette.base03,
      canvasBottom: "#001f27",
      panel: solarizedPalette.base02,
      panelMuted: "#0b3a46",
      panelSolid: "#0f3f4c",
      accent: solarizedPalette.blue,
      accentSoft: "#0f5166",
      text: solarizedPalette.base1,
      textMuted: solarizedPalette.base0,
      borderTone: solarizedPalette.base01,
      danger: solarizedPalette.red,
      success: solarizedPalette.green,
      warn: solarizedPalette.yellow,
      overlayBackdrop: "#00151b",
      modalSurface: solarizedPalette.base02,
      modalSurfaceMuted: "#0b3a46",
      modalText: solarizedPalette.base2,
      modalTextMuted: solarizedPalette.base1,
      modalBorder: solarizedPalette.base01,
      modalShadow: "#001015",
      popoverSurface: solarizedPalette.base02,
      popoverText: solarizedPalette.base2,
      popoverBorder: solarizedPalette.base01,
      surfaceRaised: solarizedPalette.base02,
      surfaceInset: solarizedPalette.base03,
      surfaceStrong: solarizedPalette.blue,
      surfaceStrongHover: "#2f95dc",
      surfaceStrongText: solarizedPalette.base03,
      focusRing: solarizedPalette.cyan,
      trendUp: solarizedPalette.green,
      trendDown: solarizedPalette.red,
      chipMutedBackground: solarizedPalette.base01,
      chipMutedBorder: solarizedPalette.base00,
      chipMutedText: solarizedPalette.base2,
      chipActiveBackground: solarizedPalette.cyan,
      chipActiveBorder: solarizedPalette.blue,
      chipActiveText: solarizedPalette.base03,
      chipWarningBackground: solarizedPalette.orange,
      chipWarningBorder: solarizedPalette.yellow,
      chipWarningText: solarizedPalette.base3,
      chipSelectedBackground: solarizedPalette.green,
      chipSelectedBorder: solarizedPalette.cyan,
      chipSelectedText: solarizedPalette.base03,
    }),
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    description: "Solarized Light with the original parchment balance, cool blue actions, and quiet text hierarchy.",
    mode: "light",
    // Solarized Light uses base01 for primary text to preserve readability on dense UI surfaces while staying inside the official palette ladder.
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: solarizedPalette.base2,
      canvas: solarizedPalette.base3,
      canvasBottom: "#ede3cd",
      panel: solarizedPalette.base3,
      panelMuted: solarizedPalette.base2,
      panelSolid: "#f6efdc",
      accent: solarizedPalette.blue,
      accentSoft: "#dceef8",
      text: solarizedPalette.base01,
      textMuted: solarizedPalette.base00,
      borderTone: solarizedPalette.base1,
      danger: solarizedPalette.red,
      success: solarizedPalette.green,
      warn: solarizedPalette.yellow,
      overlayBackdrop: solarizedPalette.base03,
      modalSurface: solarizedPalette.base3,
      modalSurfaceMuted: solarizedPalette.base2,
      modalText: solarizedPalette.base01,
      modalTextMuted: solarizedPalette.base00,
      modalBorder: solarizedPalette.base1,
      modalShadow: "#7d8b8f",
      popoverSurface: solarizedPalette.base3,
      popoverText: solarizedPalette.base01,
      popoverBorder: solarizedPalette.base1,
      surfaceRaised: solarizedPalette.base3,
      surfaceInset: solarizedPalette.base2,
      surfaceStrong: solarizedPalette.blue,
      surfaceStrongHover: "#177dc4",
      surfaceStrongText: solarizedPalette.base3,
      focusRing: solarizedPalette.cyan,
      trendUp: solarizedPalette.green,
      trendDown: solarizedPalette.red,
      chipMutedBackground: solarizedPalette.base1,
      chipMutedBorder: solarizedPalette.base0,
      chipMutedText: solarizedPalette.base3,
      chipActiveBackground: solarizedPalette.cyan,
      chipActiveBorder: solarizedPalette.blue,
      chipActiveText: solarizedPalette.base03,
      chipWarningBackground: solarizedPalette.orange,
      chipWarningBorder: solarizedPalette.yellow,
      chipWarningText: solarizedPalette.base3,
      chipSelectedBackground: solarizedPalette.green,
      chipSelectedBorder: solarizedPalette.cyan,
      chipSelectedText: solarizedPalette.base3,
    }),
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    description: "Official Gruvbox Dark warmth: walnut backgrounds, muted parchment text, and earthy highlights.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: gruvboxDarkPalette.bg1,
      canvas: gruvboxDarkPalette.bg0,
      canvasBottom: "#1d2021",
      panel: "#32302f",
      panelMuted: gruvboxDarkPalette.bg2,
      panelSolid: gruvboxDarkPalette.bg1,
      accent: gruvboxDarkPalette.orange,
      accentSoft: gruvboxDarkPalette.bg2,
      text: gruvboxDarkPalette.fg1,
      textMuted: gruvboxDarkPalette.fg4,
      borderTone: gruvboxDarkPalette.bg3,
      danger: gruvboxDarkPalette.red,
      success: gruvboxDarkPalette.green,
      warn: gruvboxDarkPalette.yellow,
      overlayBackdrop: "#141617",
      modalSurface: "#32302f",
      modalSurfaceMuted: gruvboxDarkPalette.bg1,
      modalText: gruvboxDarkPalette.fg0,
      modalTextMuted: gruvboxDarkPalette.fg3,
      modalBorder: gruvboxDarkPalette.bg3,
      modalShadow: "#141617",
      popoverSurface: "#32302f",
      popoverText: gruvboxDarkPalette.fg0,
      popoverBorder: gruvboxDarkPalette.bg3,
      surfaceRaised: gruvboxDarkPalette.bg1,
      surfaceInset: gruvboxDarkPalette.bg0,
      surfaceStrong: gruvboxDarkPalette.orange,
      surfaceStrongHover: "#ff912d",
      surfaceStrongText: "#1d2021",
      focusRing: gruvboxDarkPalette.aqua,
      trendUp: gruvboxDarkPalette.green,
      trendDown: gruvboxDarkPalette.red,
      chipMutedBackground: gruvboxDarkPalette.bg3,
      chipMutedBorder: gruvboxDarkPalette.bg2,
      chipMutedText: gruvboxDarkPalette.fg0,
      chipActiveBackground: gruvboxDarkPalette.blue,
      chipActiveBorder: gruvboxDarkPalette.aqua,
      chipActiveText: "#1d2021",
      chipWarningBackground: gruvboxDarkPalette.yellow,
      chipWarningBorder: gruvboxDarkPalette.orange,
      chipWarningText: gruvboxDarkPalette.bg1,
      chipSelectedBackground: gruvboxDarkPalette.green,
      chipSelectedBorder: gruvboxDarkPalette.aqua,
      chipSelectedText: "#1d2021",
    }),
  },
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    description: "Official Gruvbox Light parchment with dark walnut text and restrained earth-tone controls.",
    mode: "light",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: gruvboxLightPalette.bg1,
      canvas: gruvboxLightPalette.bg0,
      canvasBottom: "#f2e5bc",
      panel: "#f9f5d7",
      panelMuted: gruvboxLightPalette.bg1,
      panelSolid: gruvboxLightPalette.bg0,
      accent: gruvboxLightPalette.orange,
      accentSoft: gruvboxLightPalette.bg1,
      text: gruvboxLightPalette.fg0,
      textMuted: gruvboxLightPalette.fg4,
      borderTone: gruvboxLightPalette.bg3,
      danger: gruvboxLightPalette.red,
      success: gruvboxLightPalette.green,
      warn: gruvboxLightPalette.yellow,
      overlayBackdrop: gruvboxLightPalette.fg0,
      modalSurface: "#f9f5d7",
      modalSurfaceMuted: gruvboxLightPalette.bg1,
      modalText: gruvboxLightPalette.fg0,
      modalTextMuted: gruvboxLightPalette.fg3,
      modalBorder: gruvboxLightPalette.bg3,
      modalShadow: "#7c6f64",
      popoverSurface: "#f9f5d7",
      popoverText: gruvboxLightPalette.fg0,
      popoverBorder: gruvboxLightPalette.bg3,
      surfaceRaised: "#f9f5d7",
      surfaceInset: gruvboxLightPalette.bg1,
      surfaceStrong: gruvboxLightPalette.orange,
      surfaceStrongHover: "#c6550a",
      surfaceStrongText: gruvboxLightPalette.bg0,
      focusRing: gruvboxLightPalette.blue,
      trendUp: gruvboxLightPalette.green,
      trendDown: gruvboxLightPalette.red,
      chipMutedBackground: gruvboxLightPalette.bg3,
      chipMutedBorder: gruvboxLightPalette.bg2,
      chipMutedText: gruvboxLightPalette.bg0,
      chipActiveBackground: gruvboxLightPalette.blue,
      chipActiveBorder: gruvboxLightPalette.aqua,
      chipActiveText: gruvboxLightPalette.bg0,
      chipWarningBackground: gruvboxLightPalette.yellow,
      chipWarningBorder: gruvboxLightPalette.orange,
      chipWarningText: gruvboxLightPalette.fg0,
      chipSelectedBackground: gruvboxLightPalette.green,
      chipSelectedBorder: gruvboxLightPalette.aqua,
      chipSelectedText: gruvboxLightPalette.bg0,
    }),
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    description: "Official Catppuccin Mocha layers with deep blue-black surfaces and pastel blue-mauve controls.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: catppuccinMochaPalette.mantle,
      canvas: catppuccinMochaPalette.base,
      canvasBottom: catppuccinMochaPalette.crust,
      panel: catppuccinMochaPalette.mantle,
      panelMuted: catppuccinMochaPalette.surface0,
      panelSolid: catppuccinMochaPalette.surface1,
      accent: catppuccinMochaPalette.blue,
      accentSoft: catppuccinMochaPalette.surface0,
      text: catppuccinMochaPalette.text,
      textMuted: catppuccinMochaPalette.subtext0,
      borderTone: catppuccinMochaPalette.surface1,
      danger: catppuccinMochaPalette.red,
      success: catppuccinMochaPalette.green,
      warn: catppuccinMochaPalette.yellow,
      overlayBackdrop: catppuccinMochaPalette.crust,
      modalSurface: catppuccinMochaPalette.mantle,
      modalSurfaceMuted: catppuccinMochaPalette.surface0,
      modalText: catppuccinMochaPalette.text,
      modalTextMuted: catppuccinMochaPalette.subtext1,
      modalBorder: catppuccinMochaPalette.surface1,
      modalShadow: catppuccinMochaPalette.crust,
      popoverSurface: catppuccinMochaPalette.mantle,
      popoverText: catppuccinMochaPalette.text,
      popoverBorder: catppuccinMochaPalette.surface1,
      surfaceRaised: catppuccinMochaPalette.surface0,
      surfaceInset: catppuccinMochaPalette.base,
      surfaceStrong: catppuccinMochaPalette.mauve,
      surfaceStrongHover: "#d8b8fa",
      surfaceStrongText: catppuccinMochaPalette.base,
      focusRing: catppuccinMochaPalette.sapphire,
      trendUp: catppuccinMochaPalette.green,
      trendDown: catppuccinMochaPalette.red,
      chipMutedBackground: catppuccinMochaPalette.overlay0,
      chipMutedBorder: catppuccinMochaPalette.surface2,
      chipMutedText: catppuccinMochaPalette.text,
      chipActiveBackground: catppuccinMochaPalette.sky,
      chipActiveBorder: catppuccinMochaPalette.blue,
      chipActiveText: catppuccinMochaPalette.base,
      chipWarningBackground: catppuccinMochaPalette.peach,
      chipWarningBorder: catppuccinMochaPalette.yellow,
      chipWarningText: catppuccinMochaPalette.base,
      chipSelectedBackground: catppuccinMochaPalette.green,
      chipSelectedBorder: catppuccinMochaPalette.lavender,
      chipSelectedText: catppuccinMochaPalette.base,
    }),
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    description: "Official Catppuccin Latte: milky surfaces, ink-blue text, and bright confection accents.",
    mode: "light",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: catppuccinLattePalette.mantle,
      canvas: catppuccinLattePalette.base,
      canvasBottom: catppuccinLattePalette.crust,
      panel: "#f6f7fb",
      panelMuted: catppuccinLattePalette.surface0,
      panelSolid: catppuccinLattePalette.mantle,
      accent: catppuccinLattePalette.blue,
      accentSoft: "#dce7ff",
      text: catppuccinLattePalette.text,
      textMuted: catppuccinLattePalette.subtext0,
      borderTone: catppuccinLattePalette.surface1,
      danger: catppuccinLattePalette.red,
      success: catppuccinLattePalette.green,
      warn: catppuccinLattePalette.yellow,
      overlayBackdrop: catppuccinLattePalette.text,
      modalSurface: "#f9f9fc",
      modalSurfaceMuted: catppuccinLattePalette.mantle,
      modalText: catppuccinLattePalette.text,
      modalTextMuted: catppuccinLattePalette.subtext1,
      modalBorder: catppuccinLattePalette.surface1,
      modalShadow: "#8c8fa1",
      popoverSurface: "#f9f9fc",
      popoverText: catppuccinLattePalette.text,
      popoverBorder: catppuccinLattePalette.surface1,
      surfaceRaised: "#f9f9fc",
      surfaceInset: catppuccinLattePalette.mantle,
      surfaceStrong: catppuccinLattePalette.mauve,
      surfaceStrongHover: "#9a5cf2",
      surfaceStrongText: catppuccinLattePalette.base,
      focusRing: catppuccinLattePalette.sapphire,
      trendUp: catppuccinLattePalette.green,
      trendDown: catppuccinLattePalette.red,
      chipMutedBackground: catppuccinLattePalette.overlay0,
      chipMutedBorder: catppuccinLattePalette.surface1,
      chipMutedText: catppuccinLattePalette.base,
      chipActiveBackground: catppuccinLattePalette.sky,
      chipActiveBorder: catppuccinLattePalette.blue,
      chipActiveText: catppuccinLattePalette.base,
      chipWarningBackground: catppuccinLattePalette.peach,
      chipWarningBorder: catppuccinLattePalette.yellow,
      chipWarningText: catppuccinLattePalette.base,
      chipSelectedBackground: catppuccinLattePalette.green,
      chipSelectedBorder: catppuccinLattePalette.lavender,
      chipSelectedText: catppuccinLattePalette.base,
    }),
  },
  {
    id: "catppuccin-frappe",
    label: "Catppuccin Frappé",
    description: "Official Catppuccin Frappé dusk blues with cool midtone surfaces and soft pastel contrast.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: catppuccinFrappePalette.mantle,
      canvas: catppuccinFrappePalette.base,
      canvasBottom: catppuccinFrappePalette.crust,
      panel: catppuccinFrappePalette.mantle,
      panelMuted: catppuccinFrappePalette.surface0,
      panelSolid: catppuccinFrappePalette.surface1,
      accent: catppuccinFrappePalette.blue,
      accentSoft: catppuccinFrappePalette.surface0,
      text: catppuccinFrappePalette.text,
      textMuted: catppuccinFrappePalette.subtext0,
      borderTone: catppuccinFrappePalette.surface1,
      danger: catppuccinFrappePalette.red,
      success: catppuccinFrappePalette.green,
      warn: catppuccinFrappePalette.yellow,
      overlayBackdrop: catppuccinFrappePalette.crust,
      modalSurface: catppuccinFrappePalette.mantle,
      modalSurfaceMuted: catppuccinFrappePalette.surface0,
      modalText: catppuccinFrappePalette.text,
      modalTextMuted: catppuccinFrappePalette.subtext1,
      modalBorder: catppuccinFrappePalette.surface1,
      modalShadow: catppuccinFrappePalette.crust,
      popoverSurface: catppuccinFrappePalette.mantle,
      popoverText: catppuccinFrappePalette.text,
      popoverBorder: catppuccinFrappePalette.surface1,
      surfaceRaised: catppuccinFrappePalette.surface0,
      surfaceInset: catppuccinFrappePalette.base,
      surfaceStrong: catppuccinFrappePalette.mauve,
      surfaceStrongHover: "#d6b1ee",
      surfaceStrongText: catppuccinFrappePalette.base,
      focusRing: catppuccinFrappePalette.sapphire,
      trendUp: catppuccinFrappePalette.green,
      trendDown: catppuccinFrappePalette.red,
      chipMutedBackground: catppuccinFrappePalette.overlay0,
      chipMutedBorder: catppuccinFrappePalette.surface2,
      chipMutedText: catppuccinFrappePalette.text,
      chipActiveBackground: catppuccinFrappePalette.sky,
      chipActiveBorder: catppuccinFrappePalette.blue,
      chipActiveText: catppuccinFrappePalette.base,
      chipWarningBackground: catppuccinFrappePalette.peach,
      chipWarningBorder: catppuccinFrappePalette.yellow,
      chipWarningText: catppuccinFrappePalette.base,
      chipSelectedBackground: catppuccinFrappePalette.green,
      chipSelectedBorder: catppuccinFrappePalette.lavender,
      chipSelectedText: catppuccinFrappePalette.base,
    }),
  },
  {
    id: "catppuccin-macchiato",
    label: "Catppuccin Macchiato",
    description: "Official Catppuccin Macchiato with blue-noir depth, cool overlays, and mauve-led controls.",
    mode: "dark",
    cssVariables: buildThemeVariablesFromHex({
      canvasTop: catppuccinMacchiatoPalette.mantle,
      canvas: catppuccinMacchiatoPalette.base,
      canvasBottom: catppuccinMacchiatoPalette.crust,
      panel: catppuccinMacchiatoPalette.mantle,
      panelMuted: catppuccinMacchiatoPalette.surface0,
      panelSolid: catppuccinMacchiatoPalette.surface1,
      accent: catppuccinMacchiatoPalette.blue,
      accentSoft: catppuccinMacchiatoPalette.surface0,
      text: catppuccinMacchiatoPalette.text,
      textMuted: catppuccinMacchiatoPalette.subtext0,
      borderTone: catppuccinMacchiatoPalette.surface1,
      danger: catppuccinMacchiatoPalette.red,
      success: catppuccinMacchiatoPalette.green,
      warn: catppuccinMacchiatoPalette.yellow,
      overlayBackdrop: catppuccinMacchiatoPalette.crust,
      modalSurface: catppuccinMacchiatoPalette.mantle,
      modalSurfaceMuted: catppuccinMacchiatoPalette.surface0,
      modalText: catppuccinMacchiatoPalette.text,
      modalTextMuted: catppuccinMacchiatoPalette.subtext1,
      modalBorder: catppuccinMacchiatoPalette.surface1,
      modalShadow: catppuccinMacchiatoPalette.crust,
      popoverSurface: catppuccinMacchiatoPalette.mantle,
      popoverText: catppuccinMacchiatoPalette.text,
      popoverBorder: catppuccinMacchiatoPalette.surface1,
      surfaceRaised: catppuccinMacchiatoPalette.surface0,
      surfaceInset: catppuccinMacchiatoPalette.base,
      surfaceStrong: catppuccinMacchiatoPalette.mauve,
      surfaceStrongHover: "#d1b0f8",
      surfaceStrongText: catppuccinMacchiatoPalette.base,
      focusRing: catppuccinMacchiatoPalette.sapphire,
      trendUp: catppuccinMacchiatoPalette.green,
      trendDown: catppuccinMacchiatoPalette.red,
      chipMutedBackground: catppuccinMacchiatoPalette.overlay0,
      chipMutedBorder: catppuccinMacchiatoPalette.surface2,
      chipMutedText: catppuccinMacchiatoPalette.text,
      chipActiveBackground: catppuccinMacchiatoPalette.sky,
      chipActiveBorder: catppuccinMacchiatoPalette.blue,
      chipActiveText: catppuccinMacchiatoPalette.base,
      chipWarningBackground: catppuccinMacchiatoPalette.peach,
      chipWarningBorder: catppuccinMacchiatoPalette.yellow,
      chipWarningText: catppuccinMacchiatoPalette.base,
      chipSelectedBackground: catppuccinMacchiatoPalette.green,
      chipSelectedBorder: catppuccinMacchiatoPalette.lavender,
      chipSelectedText: catppuccinMacchiatoPalette.base,
    }),
  },
];

export const themeChoices = themeLibrary.map((theme) => theme.id) as ThemeChoice[];

export function getThemeDefinition(themeChoice?: string) {
  return themeLibrary.find((theme) => theme.id === themeChoice) ?? themeLibrary[0];
}

export function getNextThemeChoice(themeChoice: ThemeChoice) {
  const currentIndex = themeLibrary.findIndex((theme) => theme.id === themeChoice);
  return themeLibrary[(currentIndex + 1 + themeLibrary.length) % themeLibrary.length]?.id ?? themeLibrary[0].id;
}

export function cssVariableToColor(value: string, alpha?: number) {
  if (alpha === undefined) {
    return `hsl(${value})`;
  }

  return `hsl(${value} / ${alpha})`;
}
