const shellFoundationalSequences = [
  "pwd",
  "ls -la",
  "cd ~/workspace/nullkeys",
  "mkdir -p output/logs",
  "touch notes.txt",
  "cat README.md",
  "cp draft.txt archive/draft.txt",
  "mv old.log logs/old.log",
  "rm -f tmp/cache.txt",
  "git status --short",
  "npm run test",
  "find src -maxdepth 2 -type f",
  "echo \"$PWD\"",
  "printf \"%s\\n\" \"ready\"",
  "du -sh src public",
  "head -n 20 package.json",
  "wc -l README.md",
  "find public -maxdepth 1 -type f",
  "mkdir -p notes/archive",
  "cp README.md notes/archive/readme.txt",
] as const;

const shellDevelopingSequences = [
  "find . -name \"*.ts\" -maxdepth 3",
  "grep -n \"sessionKind\" src -R",
  "sed -n '1,120p' README.md",
  "tail -n 40 ./logs/dev.log",
  "env NODE_ENV=production npm run build",
  "rg -n \"difficultyBand|contentMetrics\" src tests",
  "mkdir -p \"output/release notes\"",
  "cp \"build report.txt\" ./archive/report.txt",
  "git log --oneline --decorate -5",
  "tar -czf archive.tgz src public",
  "curl -I http://127.0.0.1:4010/",
  "journalctl -n 25 --no-pager",
  "systemctl status nullkeys-preview.service",
  "docker ps --format \"table {{.Names}}\\t{{.Status}}\"",
  "find src -type f | sort | head -n 20",
  "printf \"%s\\n\" \"$PWD\" \"$SHELL\" \"$NODE_ENV\"",
  "rg -n \"persian|russian|english\" src/content",
  "cut -d, -f1 ./data/report.csv | sort | uniq -c",
  "tar -tzf handoff.tar.gz | head -n 20",
  "curl -fsSL http://127.0.0.1:4010/content-packs/manifest.json | head -n 5",
] as const;

const shellFluentSequences = [
  "npm run build > build.log 2>&1",
  "find . -type f -name \"*.tsx\" | sed -n '1,12p'",
  "git diff --stat && git status --short",
  "awk '{print $1, $3}' scores.tsv",
  "cut -d: -f1 package.json | sort -u",
  "fd session src | xargs rg -n \"progress\"",
  "xargs -0 -n1 echo < files.list",
  "cat package.json | jq '.scripts'",
  "find src -type f | sort | tail -n 12",
  "rsync -av ./src/ ./backup/src/",
  "ssh deploy@edge-host \"cd app && npm run start\"",
  "docker logs nullkeys --tail=80 --timestamps",
  "journalctl -u nullkeys -n 50 --since=2h",
  "PATH=\"$HOME/bin:$PATH\" npm run dev",
  "grep -n \"languageId\" -R src | head -n 20",
  "sed -n '1,80p' README.md > tmp/readme_excerpt.txt",
  "tar -tzf archive.tgz | rg -n \"src|public|package.json\"",
  "find public/content-packs -type f | sort | tail -n 20",
  "jq '.coverage.fullSupportLanguageCount' public/content-packs/audit-summary.json",
  "git diff -- src/content/dictionaries/language-layered-lexicons.ts | sed -n '1,80p'",
] as const;

const shellAdvancedSequences = [
  "find src -type f -name \"*.ts\" | sort | xargs rg -n \"adaptive\"",
  "rg -n --hidden --glob=\"*.tsx\" \"selectedLanguageId|selectedKeyboardLayoutId\" src",
  "tar -czf handoff.tar.gz src public package.json --exclude=node_modules",
  "git log --author=\"Kamran\" --since=\"2 weeks ago\" --oneline | head -n 15",
  "docker compose logs web --tail=120 | rg -n \"error|warn\"",
  "journalctl -u nullkeys --since=1h --follow --no-pager",
  "find . -maxdepth 2 -type d | sort | tail -n 12",
  "awk -F: '{print $1}' /etc/hosts | sort -u",
  "sed -E 's/ +/ /g' ./logs/build.log | tail -n 40",
  "env PORT=4010 HOST=127.0.0.1 npm run start",
  "ssh ops@server \"cd /srv/nullkeys && git status --short\"",
  "docker exec nullkeys-web printenv | sort | head -n 30",
  "find data -type f -name \"*.json\" | xargs jq '.version' | sort -u",
  "rg -n \"phrase-drills|quote-drills|shell-drills\" src tests | sed -n '1,40p'",
  "printf \"%s\\n\" \"active:$PWD\" \"shell:$SHELL\" \"node:$NODE_ENV\"",
  "find . -type f -print0 | xargs -0 du -h | sort -h | tail -n 10",
  "tar -tzf output/nullkeys-handoff.tgz | rg -n \"content-packs|package.json|scripts\"",
  "jq '.languages.persian' public/content-packs/audit-summary.json | sed -n '1,40p'",
  "find src tests -type f | sort | xargs rg -n \"teacher|progression|rendering\"",
  "journalctl -u nullkeys --since=30m --no-pager | rg -n \"warn|error|restart\"",
] as const;

const shellExpertSequences = [
  "find src -type f -name \"*.ts\" | sort | xargs rg -n --line-buffered \"difficultyBand|contentMetrics\" | tee output/nullkeys-patterns.log",
  "git diff --stat && git status --short && rg -n \"selectedLanguageId\" src/features | head -n 20",
  "docker logs nullkeys-web --tail=200 --timestamps 2>&1 | rg -n \"error|warn|retry\"",
  "journalctl -u nullkeys --since=\"90 min ago\" --no-pager | tail -n 80 | rg -n \"timeout|restart|bind\"",
  "find . -type f -name \"*.tsx\" -o -name \"*.ts\" | sort | xargs sed -n '1,8p' | head -n 60",
  "PATH=\"$HOME/bin:$PATH\" NODE_ENV=production npm run build > output/nullkeys-build.log 2>&1",
  "ssh ops@server \"cd /srv/nullkeys && journalctl -u nullkeys -n 40 --no-pager\"",
  "docker exec nullkeys-web sh -lc 'printenv | sort | grep -E \"NODE|PORT|HOST\"'",
  "find data -type f -print0 | xargs -0 jq -r '.id // empty' | sort -u | tail -n 25",
  "tar -czf output/nullkeys-handoff.tgz src public package.json scripts --exclude=node_modules --exclude=.next",
  "rg -n \"phrase-drills|quote-drills|shell-drills|number-drills\" src tests | sed -n '1,80p'",
  "printf \"%s\\n\" \"$PWD\" \"$SHELL\" \"branch=$(git branch --show-current)\" \"sha=$(git rev-parse --short HEAD)\"",
  "jq '.languages.russian.repetitionRobustness' public/content-packs/audit-summary.json | tee output/russian-robustness.json",
  "tar -tzf output/nullkeys-handoff.tgz | rg -n \"\\.git|node_modules|test-results\"",
  "find public/content-packs -type f -print0 | xargs -0 wc -l | sort -n | tail -n 10",
  "git diff --stat && jq '.coverage, .languages.english.benchmarkReadiness' public/content-packs/audit-summary.json",
] as const;

const shellFoundationalTerms = [
  "~/workspace/nullkeys",
  "./output/logs/latest.txt",
  "./src/features/adaptive-practice",
  "\"practice prompt\"",
  "'shell-drills'",
  "--help",
  "--json",
  "--quiet",
  "-la",
  "-n 20",
  "README.md",
  "notes/archive",
] as const;

const shellDevelopingTerms = [
  "tmp/nullkeys-report.json",
  "\"adaptive blend\"",
  "'number-drills'",
  "2>tmp/error.log",
  "> build.log",
  "NODE_ENV=production",
  "PORT=4010",
  "--maxdepth=3",
  "--follow",
  "--color=never",
  "audit-summary.json",
  "tar -tzf handoff.tar.gz",
] as const;

const shellFluentTerms = [
  "| sort | uniq -c",
  "&& echo \"done\"",
  "PATH=\"$HOME/bin:$PATH\"",
  "\"*.tsx\"",
  "'selectedLanguageId|selectedKeyboardLayoutId'",
  "--tail=120",
  "--timestamps",
  "--since=2h",
  "\"/srv/nullkeys\"",
  "\"table {{.Names}}\\t{{.Status}}\"",
  "jq '.languages.english'",
  "\"content-packs|scripts|package.json\"",
] as const;

const shellAdvancedTerms = [
  "| sed -n '1,20p'",
  "| xargs rg -n \"progress\"",
  "> tmp/readme_excerpt.txt",
  "2>&1 | tee output/build.log",
  "$(git branch --show-current)",
  "$(date +%H:%M)",
  "--line-buffered",
  "--glob=\"*.ts\"",
  "--author=\"Kamran\"",
  "\"error|warn|retry\"",
  "\"teacher|progression|rendering\"",
  "\".languages.persian\"",
] as const;

const shellExpertTerms = [
  "&& git rev-parse --short HEAD",
  "| jq -r '.version // empty'",
  "2>&1 | rg -n \"timeout|restart|bind\"",
  "\"branch=$(git branch --show-current)\"",
  "\"sha=$(git rev-parse --short HEAD)\"",
  "--exclude=node_modules",
  "--exclude=.next",
  "sh -lc 'printenv | sort'",
  "find . -type f -print0 | xargs -0",
  "\"NODE|PORT|HOST\"",
  "\".languages.russian.repetitionRobustness\"",
  "\".languages.english.benchmarkReadiness\"",
] as const;

export const shellCommandTierSequences = {
  foundational: shellFoundationalSequences,
  developing: shellDevelopingSequences,
  fluent: shellFluentSequences,
  advanced: shellAdvancedSequences,
  "expert-control": shellExpertSequences,
} as const;

export const shellCommandTermTiers = {
  foundational: shellFoundationalTerms,
  developing: shellDevelopingTerms,
  fluent: shellFluentTerms,
  advanced: shellAdvancedTerms,
  "expert-control": shellExpertTerms,
} as const;

export const programmerTokenGroups = {
  javascript: [
    "const result = items[index] ?? fallbackValue;",
    "if (value && ready) return value.trim();",
    "export async function loadEntry(id: string) {",
    "state.count += delta ?? 1;",
    "options?.theme === \"dark\" ? enable() : disable();",
    "const map = new Map<string, number>();",
    "return rows.filter((row) => row.active !== false);",
    "queue[index] = payload?.items?.[0] ?? defaultItem;",
    "type SessionShape = Record<string, string | number>;",
    "for (const [key, value] of Object.entries(source)) {",
  ],
  python: [
    "def load_entry(name: str) -> dict:",
    "if value is None: return default_map.copy()",
    "items[index] = payload.get(\"value\", 0)",
    "for line_number, row in enumerate(rows, start=1):",
    "result = [item for item in rows if item[\"ready\"]]",
    "with open(path, \"r\", encoding=\"utf-8\") as handle:",
    "command = f\"grep -n '{needle}' {path}\"",
    "settings.setdefault(\"theme\", \"light\")",
  ],
  markup: [
    "<section class=\"panel\"><code>value</code></section>",
    "<button aria-label=\"run command\">Execute</button>",
    "<input type=\"text\" placeholder=\"~/workspace\" />",
    "<meta name=\"viewport\" content=\"width=device-width\" />",
    "<a href=\"/layouts\" data-mode=\"preview\">Layouts</a>",
    "<article><header><h2>Signal</h2></header></article>",
  ],
  shell: [
    ...shellFoundationalSequences,
    ...shellDevelopingSequences,
  ],
  data: [
    "{\"speed\":72.4,\"accuracy\":98.2}",
    "[\"en\",\"ru\",\"fa\",\"ja\"]",
    "cache[key] = { hits: 4, misses: 1 };",
    "INSERT INTO sessions(speed, accuracy) VALUES(71, 98);",
    "curl -fsSL https://example.dev/install.sh | bash",
    "metrics.window.current = report.summary.avg;",
    "router.push(`/lessons/${lessonId}`);",
    "const nested = source?.nodes?.[2]?.label ?? \"idle\";",
  ],
};

export const commandLineFragments = [
  ...shellFoundationalSequences,
  ...shellDevelopingSequences,
  ...shellFluentSequences,
] as const;

export const programmerIdentifiers = [
  "sessionMetrics.netWpm",
  "progressionState.unlockPreview",
  "keyboardLayout.homeRowMap",
  "contentPlanner.difficultyBand",
  "reviewQueue.pendingItems",
  "shellPreset.commandChain",
  "report.summary.accuracyDelta",
  "responseCache.latestValue",
  "uiState.focusCharacter",
  "lessonDraft.targetSegments",
  "syntaxTheme.tokenColors",
  "passageBuilder.segmentPlan",
  "historyWindow.recentPrompts",
  "benchmarkReport.samePromptReplay",
] as const;

export const shellCommandSequences = Object.values(shellCommandTierSequences).flat() as readonly string[];

export const shellCommandTerms = Object.values(shellCommandTermTiers).flat() as readonly string[];
